### Create new department
POST http://localhost:8080/departments
Content-Type: application/json

{
  "id": 0,
  "departmentName": "engineering",
  "departmentDescription": "Technical Department"
}

> {%
    if (response.status === 201) {
        if (response.headers !== null && response.headers.valueOf('Location') !== null) {
            client.global.set('location-of-created-resource', response.headers.valueOf('Location'));
        }
    }
%}


### Get newly created department
GET {{location-of-created-resource}}
Accept: application/json

### Get all department
GET http://localhost:8080/departments/all
Accept: application/json

### Update Department Name
PATCH http://localhost:8080/departments/update/99
Content-Type: application/json

{
  "departmentDescription": "Technical Department"
}